name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          path: src

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install pyinstaller

      - name: Executable for Linux
        run: cd src && pyinstaller --onefile twitch_chatbot.py

      - name: Executable for Windows
        uses: JackMcKew/pyinstaller-action-windows@main

      - name: Upload linux executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: dist/twitch_chatbot

      - name: Upload windows build as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: windows-build
          path: dist/windows/twitch_chatbot