name: Build

on:
  push:
    branches: [ senpai ]
  pull_request:
    branches: [ senpai ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Windows build
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: src/dist/windows

    - name: Linux build
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src

    - name: Upload Windows build
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: src/dist/linux
